"""create_initial_schema

Revision ID: 0373c5682bfc
Revises: 
Create Date: 2026-10-01 01:33:29.955037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0373c5682bfc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cheques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cheque_identifier', sa.String(length=128), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('source_dataset', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cheques_created_at_status', 'cheques', ['created_at', 'status'], unique=False)
    op.create_index('idx_cheques_status_review', 'cheques', ['status', 'review_required'], unique=False)
    op.create_index(op.f('ix_cheques_cheque_identifier'), 'cheques', ['cheque_identifier'], unique=True)
    op.create_index(op.f('ix_cheques_created_at'), 'cheques', ['created_at'], unique=False)
    op.create_index(op.f('ix_cheques_image_hash'), 'cheques', ['image_hash'], unique=False)
    op.create_index(op.f('ix_cheques_review_required'), 'cheques', ['review_required'], unique=False)
    op.create_index(op.f('ix_cheques_status'), 'cheques', ['status'], unique=False)
    op.create_table('processing_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cheque_id', sa.Integer(), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detector_model_version', sa.String(length=128), nullable=False),
    sa.Column('recognizer_model_version', sa.String(length=128), nullable=False),
    sa.Column('ocr_engine_version', sa.String(length=128), nullable=False),
    sa.Column('total_latency_ms', sa.Float(), nullable=False),
    sa.Column('stage_latencies_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['cheque_id'], ['cheques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_runs_cheque_id'), 'processing_runs', ['cheque_id'], unique=False)
    op.create_index(op.f('ix_processing_runs_run_timestamp'), 'processing_runs', ['run_timestamp'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cheque_id', sa.Integer(), nullable=False),
    sa.Column('processing_run_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_confidence', sa.Float(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=32), nullable=False),
    sa.Column('confidence_tier', sa.String(length=16), nullable=False),
    sa.Column('bounding_box_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cheque_id'], ['cheques.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_extracted_fields_cheque_name', 'extracted_fields', ['cheque_id', 'field_name'], unique=False)
    op.create_index(op.f('ix_extracted_fields_cheque_id'), 'extracted_fields', ['cheque_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_confidence_tier'), 'extracted_fields', ['confidence_tier'], unique=False)
    op.create_index(op.f('ix_extracted_fields_field_name'), 'extracted_fields', ['field_name'], unique=False)
    op.create_index(op.f('ix_extracted_fields_processing_run_id'), 'extracted_fields', ['processing_run_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('processing_run_id', sa.Integer(), nullable=False),
    sa.Column('cheque_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=False),
    sa.Column('raw_confidence', sa.Float(), nullable=False),
    sa.Column('bounding_box_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cheque_id'], ['cheques.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_predictions_run_field', 'predictions', ['processing_run_id', 'field_name'], unique=False)
    op.create_index(op.f('ix_predictions_cheque_id'), 'predictions', ['cheque_id'], unique=False)
    op.create_index(op.f('ix_predictions_field_name'), 'predictions', ['field_name'], unique=False)
    op.create_index(op.f('ix_predictions_processing_run_id'), 'predictions', ['processing_run_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cheque_id', sa.Integer(), nullable=False),
    sa.Column('processing_run_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('check_type', sa.String(length=64), nullable=False),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_reason', sa.Text(), nullable=False),
    sa.Column('review_priority', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('review_resolution', sa.String(length=32), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cheque_id'], ['cheques.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_validation_cheque_status', 'validation_results', ['cheque_id', 'validation_status'], unique=False)
    op.create_index(op.f('ix_validation_results_check_type'), 'validation_results', ['check_type'], unique=False)
    op.create_index(op.f('ix_validation_results_cheque_id'), 'validation_results', ['cheque_id'], unique=False)
    op.create_index(op.f('ix_validation_results_field_name'), 'validation_results', ['field_name'], unique=False)
    op.create_index(op.f('ix_validation_results_processing_run_id'), 'validation_results', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_validation_results_validation_status'), 'validation_results', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_validation_status'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_processing_run_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_field_name'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_cheque_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_check_type'), table_name='validation_results')
    op.drop_index('idx_validation_cheque_status', table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_predictions_processing_run_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_field_name'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_cheque_id'), table_name='predictions')
    op.drop_index('idx_predictions_run_field', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_extracted_fields_processing_run_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_field_name'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_confidence_tier'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_cheque_id'), table_name='extracted_fields')
    op.drop_index('idx_extracted_fields_cheque_name', table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_processing_runs_run_timestamp'), table_name='processing_runs')
    op.drop_index(op.f('ix_processing_runs_cheque_id'), table_name='processing_runs')
    op.drop_table('processing_runs')
    op.drop_index(op.f('ix_cheques_status'), table_name='cheques')
    op.drop_index(op.f('ix_cheques_review_required'), table_name='cheques')
    op.drop_index(op.f('ix_cheques_image_hash'), table_name='cheques')
    op.drop_index(op.f('ix_cheques_created_at'), table_name='cheques')
    op.drop_index(op.f('ix_cheques_cheque_identifier'), table_name='cheques')
    op.drop_index('idx_cheques_status_review', table_name='cheques')
    op.drop_index('idx_cheques_created_at_status', table_name='cheques')
    op.drop_table('cheques')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
