"""Database persistence layer for ChequeSense."""

from src.database.connection import (
    Base,
    build_database_url,
    check_db_connection,
    db_session_scope,
    get_db,
    get_engine,
    init_db,
)
from src.database.crud import (
    bulk_create_extracted_fields,
    bulk_create_predictions,
    bulk_create_validation_results,
    create_cheque,
    create_processing_run,
    create_user,
    get_cheque_by_hash,
    get_cheque_by_id,
    get_cheque_by_identifier,
    get_fields_for_cheque,
    get_processing_run_by_id,
    get_user_by_email,
    get_user_by_id,
    get_user_by_username,
    list_cheques,
    list_runs_for_cheque,
    list_users,
    save_pipeline_execution,
    update_cheque_status,
    update_review_resolution,
)
from src.database.models import (
    Cheque,
    ExtractedField,
    Prediction,
    ProcessingRun,
    User,
    ValidationResult,
)
from src.database.schemas import (
    ChequeCreate,
    ChequeDetailResponse,
    ChequeResponse,
    ExtractedFieldCreate,
    ExtractedFieldResponse,
    PredictionCreate,
    PredictionResponse,
    ProcessingRunCreate,
    ProcessingRunResponse,
    UserCreate,
    UserResponse,
    ValidationResultCreate,
    ValidationResultResponse,
)

__all__ = [
    # Connection
    "Base",
    "get_engine",
    "get_db",
    "db_session_scope",
    "check_db_connection",
    "init_db",
    "build_database_url",
    # Models
    "User",
    "Cheque",
    "ProcessingRun",
    "Prediction",
    "ExtractedField",
    "ValidationResult",
    # Schemas
    "UserCreate",
    "UserResponse",
    "ChequeCreate",
    "ChequeResponse",
    "ChequeDetailResponse",
    "ExtractedFieldCreate",
    "ExtractedFieldResponse",
    "PredictionCreate",
    "PredictionResponse",
    "ValidationResultCreate",
    "ValidationResultResponse",
    "ProcessingRunCreate",
    "ProcessingRunResponse",
    # CRUD
    "create_user",
    "get_user_by_id",
    "get_user_by_username",
    "get_user_by_email",
    "list_users",
    "create_cheque",
    "get_cheque_by_id",
    "get_cheque_by_identifier",
    "get_cheque_by_hash",
    "list_cheques",
    "update_cheque_status",
    "create_processing_run",
    "get_processing_run_by_id",
    "list_runs_for_cheque",
    "bulk_create_predictions",
    "bulk_create_extracted_fields",
    "get_fields_for_cheque",
    "bulk_create_validation_results",
    "update_review_resolution",
    "save_pipeline_execution",
]
