"""Manifest generation and annotation formatting for ChequeSense.

Generates machine-readable JSON and CSV manifests uniting all datasets with
their assigned splits, image dimensions, bounding boxes, OCR text, and
provenance metadata.
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import os
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd
from PIL import Image

from src.data.dataset_loader import ChequeSample, DatasetLoader
from src.data.split_data import DataSplitter


class ManifestBuilder:
    """Constructs comprehensive manifests and COCO-style annotation files."""

    def __init__(
        self,
        base_dir: str = "Dataset",
        splits_dir: str = "data/splits",
        manifests_dir: str = "data/manifests",
        annotations_dir: str = "data/annotations",
        raw_cache_dir: str = "data/raw",
    ):
        self.loader = DatasetLoader(base_dir=base_dir)
        self.splits_dir = Path(splits_dir)
        self.manifests_dir = Path(manifests_dir)
        self.annotations_dir = Path(annotations_dir)
        self.raw_cache_dir = Path(raw_cache_dir)

        self.manifests_dir.mkdir(parents=True, exist_ok=True)
        self.annotations_dir.mkdir(parents=True, exist_ok=True)
        self.raw_cache_dir.mkdir(parents=True, exist_ok=True)

    def load_split_mappings(self) -> Dict[str, str]:
        """Loads split assignments generated by DataSplitter."""
        combined_map: Dict[str, str] = {}

        syn_file = self.splits_dir / "synthetic_splits.json"
        if syn_file.exists():
            with open(syn_file) as f:
                syn_data = json.load(f)
                combined_map.update(syn_data.get("sample_to_split", {}))

        hw_file = self.splits_dir / "handwritten_splits.json"
        if hw_file.exists():
            with open(hw_file) as f:
                hw_data = json.load(f)
                combined_map.update(hw_data.get("sample_to_split", {}))

        idrbt_file = self.splits_dir / "idrbt_splits.json"
        if idrbt_file.exists():
            with open(idrbt_file) as f:
                idrbt_data = json.load(f)
                combined_map.update(idrbt_data.get("sample_to_split", {}))

        return combined_map

    def save_raw_image(self, sample: ChequeSample, subfolder: str) -> str:
        """Saves image bytes to data/raw/<subfolder>/ and returns relative path."""
        target_dir = self.raw_cache_dir / subfolder
        target_dir.mkdir(parents=True, exist_ok=True)

        ext = ".png" if sample.dataset_name == "synthetic" else ".jpg"
        if sample.source_dataset == "IDRBT":
            ext = ".tif"

        out_fname = f"{sample.sample_id}{ext}"
        out_path = target_dir / out_fname

        if not out_path.exists():
            img = sample.get_image()
            if ext == ".tif":
                img.save(out_path, format="TIFF")
            elif ext == ".png":
                img.save(out_path, format="PNG")
            else:
                img.save(out_path, format="JPEG")

        return str(out_path.relative_to(Path.cwd()))

    def build_all(self, cache_images_to_raw: bool = False) -> Dict[str, Any]:
        """Builds all manifests and COCO annotations.

        Args:
            cache_images_to_raw: If True, writes individual image files to data/raw/
                                 so downstream pipelines can load directly from disk.
        """
        # Ensure splits exist
        split_map = self.load_split_mappings()
        if not split_map:
            splitter = DataSplitter(base_dir=str(self.loader.base_dir), output_dir=str(self.splits_dir))
            splitter.run_all_splits()
            split_map = self.load_split_mappings()

        records: List[Dict[str, Any]] = []
        hash_counts: Dict[str, int] = defaultdict(int)

        # 1. Collect all samples
        all_samples: List[ChequeSample] = []
        all_samples.extend(list(self.loader.load_synthetic(split=None)))
        all_samples.extend(list(self.loader.load_handwritten_and_cheques(split=None)))
        all_samples.extend(list(self.loader.load_idrbt(lazy=True)))

        for s in all_samples:
            if s.image_hash:
                hash_counts[s.image_hash] += 1

        # 2. Build records
        for s in all_samples:
            assigned_split = split_map.get(s.sample_id, s.source_split or "unsplit")
            is_dup = hash_counts[s.image_hash] > 1

            if cache_images_to_raw:
                subfolder = s.dataset_name
                rel_img_path = self.save_raw_image(s, subfolder)
            else:
                rel_img_path = s.source_file

            record = {
                "sample_id": s.sample_id,
                "dataset_name": s.dataset_name,
                "source_dataset": s.source_dataset,
                "source_file": s.source_file,
                "image_path": rel_img_path,
                "image_width": s.width,
                "image_height": s.height,
                "color_mode": s.color_mode,
                "image_hash": s.image_hash,
                "split": assigned_split,
                "labels": s.labels,
                "annotation_type": s.annotation_type,
                "annotations": s.annotations,
                "is_duplicate": is_dup,
                "duplicate_group": s.image_hash if is_dup else None,
                "metadata": s.metadata,
            }
            records.append(record)

        # 3. Save JSON master manifest
        json_path = self.manifests_dir / "dataset_manifest.json"
        with open(json_path, "w") as f:
            json.dump(records, f, indent=2)

        # 4. Save CSV manifest (flattening annotations to JSON strings)
        csv_path = self.manifests_dir / "dataset_manifest.csv"
        csv_fields = [
            "sample_id",
            "dataset_name",
            "source_dataset",
            "image_path",
            "image_width",
            "image_height",
            "color_mode",
            "image_hash",
            "split",
            "labels",
            "annotation_type",
            "annotations_json",
            "is_duplicate",
            "duplicate_group",
        ]

        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=csv_fields)
            writer.writeheader()
            for r in records:
                writer.writerow({
                    "sample_id": r["sample_id"],
                    "dataset_name": r["dataset_name"],
                    "source_dataset": r["source_dataset"],
                    "image_path": r["image_path"],
                    "image_width": r["image_width"],
                    "image_height": r["image_height"],
                    "color_mode": r["color_mode"],
                    "image_hash": r["image_hash"],
                    "split": r["split"],
                    "labels": "|".join(r["labels"]),
                    "annotation_type": r["annotation_type"],
                    "annotations_json": json.dumps(r["annotations"]),
                    "is_duplicate": r["is_duplicate"],
                    "duplicate_group": r["duplicate_group"] or "",
                })

        # 5. Save split-specific manifests
        split_records: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
        for r in records:
            split_records[r["split"]].append(r)

        for sp, recs in split_records.items():
            sp_path = self.manifests_dir / f"{sp}_manifest.json"
            with open(sp_path, "w") as f:
                json.dump(recs, f, indent=2)

        # 6. Generate COCO Annotations for Synthetic Cheques
        self.generate_synthetic_coco_annotations(records)

        dataset_counts = {str(k): int(v) for k, v in pd.DataFrame(records)["dataset_name"].value_counts().items()}

        summary = {
            "total_records": len(records),
            "manifest_json": str(json_path),
            "manifest_csv": str(csv_path),
            "splits": {sp: len(recs) for sp, recs in split_records.items()},
            "datasets": dataset_counts,
        }
        return summary


    def generate_synthetic_coco_annotations(self, records: List[Dict[str, Any]]) -> None:
        """Exports synthetic bounding boxes to standardized COCO detection format."""
        category_map = {
            "date": 1,
            "amount": 2,
            "ifsc": 3,
            "acno": 4,
            "sign": 5,
            "name": 6,
        }
        categories = [{"id": cid, "name": cname} for cname, cid in category_map.items()]

        coco_by_split: Dict[str, Dict[str, Any]] = {
            "train": {"images": [], "annotations": [], "categories": categories},
            "val": {"images": [], "annotations": [], "categories": categories},
            "test": {"images": [], "annotations": [], "categories": categories},
        }

        ann_id = 1
        img_id_map: Dict[str, int] = {}
        curr_img_id = 1

        for r in records:
            if r["dataset_name"] != "synthetic":
                continue

            sp = r["split"]
            if sp not in coco_by_split:
                continue

            img_id = curr_img_id
            curr_img_id += 1

            coco_by_split[sp]["images"].append({
                "id": img_id,
                "file_name": r["image_path"],
                "width": r["image_width"],
                "height": r["image_height"],
                "sample_id": r["sample_id"],
                "image_hash": r["image_hash"],
            })

            bboxes = r["annotations"]
            for field_name, coords in bboxes.items():
                if field_name not in category_map:
                    continue
                xmin = coords["xmin"]
                ymin = coords["ymin"]
                xmax = coords["xmax"]
                ymax = coords["ymax"]
                bbox_w = xmax - xmin
                bbox_h = ymax - ymin
                area = bbox_w * bbox_h

                coco_by_split[sp]["annotations"].append({
                    "id": ann_id,
                    "image_id": img_id,
                    "category_id": category_map[field_name],
                    "bbox": [xmin, ymin, bbox_w, bbox_h],
                    "area": area,
                    "iscrowd": 0,
                })
                ann_id += 1

        for sp, data in coco_by_split.items():
            coco_path = self.annotations_dir / f"synthetic_coco_{sp}.json"
            with open(coco_path, "w") as f:
                json.dump(data, f, indent=2)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build ChequeSense manifests and COCO annotations.")
    parser.add_argument("--base_dir", default="Dataset", help="Raw dataset base directory")
    parser.add_argument("--cache_images", action="store_true", help="Extract raw images to data/raw/")
    args = parser.parse_args()

    builder = ManifestBuilder(base_dir=args.base_dir)
    res = builder.build_all(cache_images_to_raw=args.cache_images)
    print("Manifest generation complete:")
    print(json.dumps(res, indent=2))
